on:
  push:
    branches: master
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: build&deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          npm install
          npm run build

      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          server: "${{ secrets.SERVER }}"
          uername: "${{ secrets.USERNAME }}"
          ssh_private_key: ${{ secrets.SSH_KEY }}
          local_path: "./dist/"
          args: "-o ConnectTimeout=5"
